#!/usr/bin/env bash

emulator_path="${HOME}/Library/Android/sdk/emulator/emulator"

subcommand="${1}"

case "${subcommand}" in
  "list" )
    echo "$(${emulator_path} -list-avds)" ;;
  "start" )
    if [ -z "${2}" ]; then
      avd="$(${emulator_path} -list-avds | fzf)"
      ${emulator_path} -avd "${avd}" -netdelay none -netspeed full -dns-server 8.8.8.8
    else
      ${emulator_path} -avd "${2}" -netdelay none -netspeed full -dns-server 8.8.8.8
    fi
    ;;
  * )
    echo "Unavailble subcommand"
    exit 1
    ;;
esac
