#!/usr/bin/env bash
{

git fetch
dest_branch="$(git branch -a | fzf)"
if [ $? -ne 0 ]; then
  exit 1
fi

dest_branch="${dest_branch//\ /}"
if [ $? -ne 0 ]; then
  exit 1
fi

if [ -z "${dest_branch}" ]; then
  exit 2
fi

if [[ "${dest_branch}" =~ \* ]]; then
  echo "Already in the branch"
fi

echo "Checkout to ${dest_branch}"

if [[ "${dest_branch}" =~ remotes ]]; then
  git checkout -b "${dest_branch//remotes\/origin\//}" "${dest_branch//remotes\//}"
elif [[ "${dest_branch}" =~ \* ]]; then
  echo "Already in the branch"
else
  git checkout "${dest_branch}"
fi

}
