#!/usr/bin/env bash

set -Ceu

{

# git fetch --prune

branches=$(git --no-pager reflog | awk '$3 == "checkout:" && /moving from/ {print $8}')
dest_branch="$(echo "${branches}" | fzf)"

git checkout "${dest_branch}"

}
