#!/usr/bin/env bash

set -Ceu

{

branches=$(git --no-pager reflog | awk '$3 == "checkout:" && /moving from/ {print $8}')
# awk ... is deduplication
dest_branch="$(echo "${branches}" | awk '!seen[$0]++' | fzf)"

git checkout "${dest_branch}"

}
