#!/bin/bash
set -Ceu

format="${1}"
infile="${2}"
remove_ext="${infile/\.wav/}"
cmd=""

case "$format" in
  "mp3"  ) cmd="lame ${infile}" ;;
  "ogg"  ) cmd="oggenc ${infile}" ;;
  "flac" ) cmd="flac ${infile}" ;;
  "opus" ) cmd="opusenc ${infile} ${remove_ext}.opus" ;;
esac

if [ "${cmd}" != "" ]; then
  eval "${cmd}"
fi
