#!/bin/bash
# Copyright 2018 kanenobu mitsuru
# free pascal compile and remove middle file

if fpc "$1";then
    excutable="${1/.pas/}"
    if [ -e "$excutable".o ];then
        rm "$excutable".o
    fi
fi

