#!/bin/bash
# Copyright 2018 kanenobu mitsuru
# free pascal compile and remove middle file

_fpc2() {
  /usr/bin/fpc "$@" 2>/dev/null
  result=$?
  if [ $result -eq 0 ]; then
    if [ -e "$excutable".o ];then
        rm "$excutable".o
    fi
  fi
}

_fpc2 "$@"
