#!/bin/bash
# free pascal compie and run

excutable="$(echo "$1" | sed -e "s/\.pas//")"
fpc "$1"
result="$?"
if [ -e "$excutable".o ];then
    rm "$excutable".o
fi

if [ "$result" -eq 0 ];then
    "$excutable"
fi

if [ -e "$excutable" ];then
    rm "$excutable"
fi
