#!/bin/bash
## git push current branch name

gpoc(){
  # Prevent push to "master" option
  safe_guard="true"
  current_branch="$(git symbolic-ref --short HEAD)"
  pushDest="$(git remote show origin | grep "mkanenobu")"
  following_branch="$(git branch -vv | cut -d[ -f2 | cut -d] -f1)"
  echo "Push to ${current_branch}"
  # 自分のリポジトリならmasterでもプッシュ
  if [ -n "${pushDest}" ]; then
    if [ -n "${following_branch}" ]; then
      git push "${following_branch}"
    else
      git push origin "${current_branch}"
    fi
  else
    if [[ "${current_branch}" =~ (master|release|develop) ]]; then
      if [ "${safe_guard}" == "true" ]; then
        echo "Don't allow to push to master, release, develop"
        exit 1
      else
        echo "You are going to push to ${current_branch}"
        read -rp "Are you sure?(Yes/No):" confirm
        if [ "${confirm}" == "Yes" ]; then
          git push origin "${current_branch}"
        else
          echo "If you want to push, Type 'Yes'"
        fi
      fi
    else
      git push origin "${current_branch}"
    fi
  fi
}

gpoc
