#!/bin/bash
### Execute ":doc $1" in GHCi

if [ $# -eq 0 ];then
  exit 1
fi

s="""
:t ${1}
:doc ${1}
"""

echo "$s" | stack ghci 2>/dev/null | tail -n +3 | sed -e "s/Prelude> //g" -e "/Leaving GHCi./d"

