#!/bin/bash

set -Ce

if [ $# -eq 0 ]; then
  exit 1
fi

input=""
# Use clipboard as stdin (with stdin option)
if [ "$1" == "--stdin" ]; then
  input="$(pbpaste)"
  shift
fi

source_file="$1"

if [ -n "${input}" ]; then
  echo "${input}" | nim c --run --verbosity:0 -d:ssl "$source_file"
else
  nim c --run --verbosity:0 -d:ssl "$source_file"
fi

rm -f "${source_file/.nim/}"
