#!/bin/bash
EVENT="shell_notify"
KEY="<your key>"
URL="https://maker.ifttt.com/trigger/$EVENT/with/key/$KEY"
CURL="$(which curl)"

if [ "$#" -eq 0 ]; then
    exit 1
elif [ "$KEY" = "<your key>" ]; then
    echo "Edit this file"
    exit 1
fi

send_notification(){
    "$CURL" -X POST \
        "$URL" \
        --header "Content-Type: application/json" \
        --data-binary "{\"value1\": \"$PROCESS\"}"
}

PROCESS="${*:1}"
eval "time $PROCESS"
PROCESS_ID="$!"

while true; do
    kill -0 "$PROCESS_ID" >/dev/null 2>&1
    if [ "$?" != 0 ]; then
        echo "done"
        send_notification
        echo
        break
    fi
    sleep 5
done
