#!/usr/bin/env bash


### ocamlbuild wrapper

if [[ ${1} =~ (|-|--)help  ]]; then
  echo "USAGE: ob [OPTIONS] [FILENAME]"
  echo "  This script is wrapper of ocamlbuild"
  echo 
  echo "OPTIONS:"
  echo "  -o: Output file name"
fi

sourcefile="${!#}"
path="$(dirname "${sourcefile}")"
filename="$(basename "${sourcefile}")"
filename_wo_ext="${filename%.*}"
excutablename="${filename_wo_ext}"

options="${@:1:$#-1}"

if [ ! -f "${sourcefile}" ]; then
  echo "File not found"
  exit 1
fi

cd "${path}" && ocamlbuild -use-ocamlfind -pkg core -pkg base -pkg spotlib -tag thread ${options} "${filename_wo_ext}.native" \
  && unlink "${filename_wo_ext}.native" \
  && cp _build/"${filename_wo_ext}.native" ./"${excutablename}"

if [ -x "_build/${filename_wo_ext}.native" ]; then
  rm _build/${filename_wo_ext}.native
fi

if [ -e "_build/${filename_wo_ext}.o" ]; then
  rm _build/${filename_wo_ext}.o
fi
