#!/usr/bin/env bash
set -Cue

### ocamlbuild wrapper

if [[ ${1} =~ (|-|--)help  ]]; then
  echo "USAGE: obrun [OPTIONS] [FILENAME]"
  echo "  This script is wrapper of ocamlbuild"
fi

sourcefile="${!#}"
exec_file="$(readlink -f ${sourcefile%.*})"

ob -quiet "${@}"

if [ -x "${exec_file}" ]; then
  ${exec_file}
fi

if [ -x "${exec_file}" ]; then
  rm "${exec_file}"
fi

