#!/usr/bin/env bash

### ocamlbuild wrapper

if [[ ${1} =~ (|-|--)help  ]]; then
  echo "USAGE: obrun [OPTIONS] [FILENAME]"
  echo "  This script is wrapper of ocamlbuild"
fi

sourcefile="${!#}"
path="$(dirname "${sourcefile}")"
filename="$(basename "${sourcefile}")"
filename_wo_ext="${filename%.*}"
excutablename="${filename_wo_ext}"

options="${@:1:$#-1}"

cd "${path}" && ocamlbuild -lib unix -lib str ${options} "${filename_wo_ext}.native"

if [ -x "./${filename_wo_ext}.native" ]; then
  ./${filename_wo_ext}.native
fi

if [ -x "./${filename_wo_ext}" ]; then
  rm "./${filename_wo_ext}"
fi

if [ -e "${filename_wo_ext}.native" ]; then
  unlink "${filename_wo_ext}.native"
fi

if [ -d "./_build" ]; then
  rm -rf _build/${filename_wo_ext}.*
fi

