#!/usr/bin/env bash

### ocamlbuild wrapper

if [[ ${1} =~ (|-|--)help  ]]; then
  echo "USAGE: ob [OPTIONS] [FILENAME]"
  echo "  This script is wrapper of ocamlbuild"
  echo 
  echo "OPTIONS:"
  echo "  -o: Output file name"
fi

sourcefile="${!#}"
path="$(dirname "${sourcefile}")"
filename="$(basename "${sourcefile}")"
filename_wo_ext="${filename%.*}"
excutablename="${filename_wo_ext}"

flag_excutablename=false

for opt in "${@:1:$#-1}"; do
  if ${flag_excutablename}; then
    excutablename="${opt}"
    flag_excutablename=false
  fi
  case "$opt" in
    "-o" ) flag_excutablename=true ;;
  esac
done

if [ ! -f "${sourcefile}" ]; then
  echo "File not found"
  exit 1
fi

cd "${path}" && ocamlbuild "${filename_wo_ext}.native" \
  && unlink "${filename_wo_ext}.native" \
  && mv _build/"${filename_wo_ext}.native" ./"${excutablename}"

if [ -d "_build" ]; then
  rm -r "_build"
fi


