#!/usr/bin/env bash

### ocamlbuild wrapper

if [[ ${1} =~ (|-|--)help  ]]; then
  echo "USAGE: ocrun [FILENAME]"
  echo "  This script is wrapper of ocamlbuild"
fi

sourcefile="${!#}"
path="$(dirname "${sourcefile}")"
filename="$(basename "${sourcefile}")"
filename_wo_ext="${filename%.*}"

if [ ! -f "${sourcefile}" ]; then
  echo "File not found"
  exit 1
fi

cd "${path}" && ocamlbuild "${filename_wo_ext}.native" \
  && unlink "${filename_wo_ext}.native" \
  && mv _build/"${filename_wo_ext}.native" ./"${filename_wo_ext}"

if [ -d "_build" ]; then
  rm -r "_build"
fi

if [ -x "./${filename_wo_ext}" ]; then
  ./${filename_wo_ext}
fi

if [ -x "./${filename_wo_ext}" ]; then
  rm "./${filename_wo_ext}"
fi
