#!/bin/bash
### Script runner for multi language

source_file="$1"
file_extension="$(echo "$source_file" | sed 's/^.*\.\([^\.]*\)$/\1/')"
options="${@:2}"
runner=""

user_setting_location="$HOME/.config/runner/user_runner"
if [ -e "$user_setting_location" ]; then
  source "$user_setting_location"
fi

shebang="$(head -n 1 "$source_file")"

if [[ "$shebang" =~ \#\!/ ]]; then
  runner="${shebang//\#\!//}" "$source_file" "$options"
else
  case "$file_extension" in
    "nim" ) runner="nim_run";;
    "pas" ) runner="pascal_run";;
    "cl" | "lisp" ) runner="common_lisp_run";;
    * ) echo "File is not supported"; exit
  esac
fi

if [ -n "$runner" ]; then
  eval "$runner" "$source_file" "$options"
fi
