[package]
name = "jsonl-stream-prettify"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored_json = "5.0.0"
sonic-rs = "0.3"
termcolor = "1.4"
